<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sistemaSolar [
    <!ELEMENT sistemaSolar (cuerpo*)>
    <!ELEMENT cuerpo ((planeta | satelite | asteroide)+)>
    <!ELEMENT planeta (#PCDATA)>
    <!ELEMENT satelite (#PCDATA)>
    <!ELEMENT asteroide (#PCDATA)>
]>
<sistemaSolar>
    <cuerpo>
        <planeta>Tierra</planeta>
        <satelite>Luna</satelite>
        <asteroide>Ceres</asteroide>
    </cuerpo>
</sistemaSolar>