=== obiticadev/DAM-2025-26/Lenguaje de marcas/Tema_5/XSD/Bloque II/02 Inventario de almacén/almacen.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="almacen">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="articulo" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="descripcion" type="xs:string" />
                            <xs:element name="cantidad" type="tipoCantidad" />
                            <xs:element name="ubicacion" type="tipoUbicacion" />
                        </xs:sequence>
                        <xs:attribute name="codigo" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="tipoCantidad">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipoUbicacion">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Zona-A" />
            <xs:enumeration value="Zona-B" />
            <xs:enumeration value="Zona-C" />
            <xs:enumeration value="Refrigerado" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== obiticadev/DAM-2025-26/Lenguaje de marcas/Tema_5/XSD/Bloque II/02 Inventario de almacén/almacen.xml
<?xml version="1.0" encoding="UTF-8"?>
<almacen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="almacen.xsd">
    <articulo codigo="001">
        <descripcion>Esta es la primera descripción</descripcion>
        <cantidad>0</cantidad>
        <ubicacion>Zona-A</ubicacion>
    </articulo>
    <articulo codigo="002">
        <descripcion>Esta es la segunda descripción</descripcion>
        <cantidad>4</cantidad>
        <ubicacion>Zona-B</ubicacion>
    </articulo>
    <articulo codigo="003">
        <descripcion>Esta es la tercera descripción</descripcion>
        <cantidad>7</cantidad>
        <ubicacion>Refrigerado</ubicacion>
    </articulo>
</almacen>
