=== obiticadev/DAM-2025-26/Lenguaje de marcas/Tema_5/XSD/Bloque I/07 Menú de restaurante/menu.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="menu">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="plato"
                    minOccurs="2"
                    maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre"
                                type="xs:string" />
                            <xs:element name="precio"
                                type="xs:decimal" />
                            <xs:element name="calorias" type="xs:decimal" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== obiticadev/DAM-2025-26/Lenguaje de marcas/Tema_5/XSD/Bloque I/07 Menú de restaurante/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<menu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="menu.xsd">
    <plato>
        <nombre>Paella Valenciana</nombre>
        <precio>14.50</precio>
        <calorias>850</calorias>
    </plato>
    <plato>
        <nombre>Gazpacho</nombre>
        <precio>10</precio>
        <calorias>100</calorias>
    </plato>
</menu>
